# 编译阶段 命名为 builder
# 引用镜像
FROM node:13.1.0-stretch as builder

# 作者
MAINTAINER luxc

# 执行命令，创建文件夹
RUN mkdir -p /home/vueapp
# 将项目源码拷贝到镜像里
ADD . /home/vueapp
# 指定工作目录
WORKDIR /home/vueapp

#安装nrm
RUN npm install -g nrm

# 设置私服，下载自定义控件需要
RUN nrm add lzyy https://repo.lzyy.cn/repository/npm-public/

# 使用lzyy私服
RUN nrm use lzyy

# 安装依赖及构建node应用
RUN npm install
RUN npm run test

# 配置系统变量，指定端口
#ENV HOST 0.0.0.0
#ENV PORT 8080

# 将端口8081开放
#EXPOSE 8080
# 容器启动命令
#CMD ["npm", "start"]

# 运行阶段
FROM nginx:alpine
# 从编译阶段的中拷贝编译结果到当前镜像中
COPY --from=builder /home/vueapp/dist /var/www/html
COPY ./custom.conf /etc/nginx/conf.d/default.conf
#RUN rm /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx","-g","daemon off;"]